-- AlterTable
ALTER TABLE "User" ADD COLUMN     "alcohol_consumption" BOOLEAN,
ADD COLUMN     "allergic_history" TEXT,
ADD COLUMN     "balanced_diet" BOOLEAN,
ADD COLUMN     "contraceptive_method" TEXT,
ADD COLUMN     "diabetes_type" TEXT,
ADD COLUMN     "epilepsy" BOOLEAN,
ADD COLUMN     "exercise_duration" TEXT,
ADD COLUMN     "has_children" TEXT,
ADD COLUMN     "hypertension" BOOLEAN,
ADD COLUMN     "hypotension" BOOLEAN,
ADD COLUMN     "is_pregnant" BOOLEAN,
ADD COLUMN     "is_smoker" BOOLEAN,
ADD COLUMN     "lesions_present" BOOLEAN,
ADD COLUMN     "long_sitting" BOOLEAN,
ADD COLUMN     "medical_treatment" TEXT,
ADD COLUMN     "menstrual_cycle" TEXT,
ADD COLUMN     "metal_presence" TEXT,
ADD COLUMN     "oncologic_history" TEXT,
ADD COLUMN     "orthopedic_issues" TEXT,
ADD COLUMN     "pacemaker_present" BOOLEAN,
ADD COLUMN     "previous_cosmetic" BOOLEAN,
ADD COLUMN     "regular_bowel_function" BOOLEAN,
ADD COLUMN     "skin_acids_usage" TEXT,
ADD COLUMN     "surgical_history" TEXT,
ADD COLUMN     "varicose_veins" BOOLEAN,
ADD COLUMN     "water_consumption" BOOLEAN;
